### ISSUE TITLE
bookshelf-scopes...

### ISSUE THREAD

**Issue by evgarik** [adobnikar/bookshelf-eloquent#1]
There is an opportunity to use together bookshelf-eloquent and bookshelf-scopes?

Thank you for the implementation of!

**Comment by adobnikar** [comment]
Thank you for your request. I will try to implement the support for bookshelf-scopes as soon as possible.

**Comment by evgarik** [comment]
Thank you. I'm waiting impatiently

**Comment by adobnikar** [comment]
Is this one ok too?

**Comment by evgarik** [comment]
I'ts ok too!
Thank you
