### ISSUE TITLE
'with' with virtuals causing error 

### ISSUE THREAD

**Issue by pramjeet** [adobnikar/bookshelf-eloquent#3]
Let's assume I have two models, company and user.
'User' has a virtual field 'fullName'.

If I do something like this:

```
Company
.where({id:id})
.with(['user'])
.first()
```
it gives the following error

`Cannot set property fullName of [object Object] which has only a getter`

**Comment by adobnikar** [comment]
I managed to replicate it by defining a virtual property that only has a getter on the user model. Is that right?
I will look into it.

**Comment by adobnikar** [comment]
I published a new patch. I would love to get feedback from you. Let me know if your issue was fixed.

**Comment by pramjeet** [comment]
Thanks for the quick reply man!! 
Yes, with a virtual property with getter only, sorry I forgot to mention that. 
Will try the patch in few hours, and will definitely give feedback.

**Comment by pramjeet** [comment]
The bug is fixed for me after the patch.

Thanks again man!!
